@startuml

' Задание 1.1

class Автомобиль {
    -мощность: целое_число
    -стоимость: вещественное_число
    -номер: строка
    -марка: строка
    +запуститьДвигатель()
    +ускориться()
    +тормозить()
}

class Компания {
    -название: строка
    -адрес: строка
    -сотрудники: Список<Сотрудник>
    +добавитьСотрудника(сотрудник: Сотрудник)
    +удалитьСотрудника(сотрудник: Сотрудник)
    +получитьПрибыль()
}

class РедакцияГазеты {
    -название: строка
    -адрес: строка
    -штат: Список<Журналист>
    -статьи: Список<Статья>
    +добавитьСтатью(статья: Статья)
    +опубликовать()
}

' Задание 1.2
abstract ТранспортноеСредство {
    -мощность: целое_число
    -стоимость: вещественное_число
    -номер: строка
    -марка: строка
}

Автомобиль --|> ТранспортноеСредство
class Автомобиль {
    -пробег: целое_число
    -пройденТехосмотр: логическое_значение
    +ехать()
}

Самолет --|> ТранспортноеСредство
class Самолет {
    -максимальнаяВысотаПолета: целое_число
    +лететь()
}

@enduml